// <auto-generated />
using System;
using HelpDeskSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDeskSystem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217152520_MejorasMnualesFinal")]
    partial class MejorasMnualesFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelpDeskSystem.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Nombre = "Sistema Financiero"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Nombre = "Sistema Genesis"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Nombre = "Reportes"
                        });
                });

            modelBuilder.Entity("HelpDeskSystem.Domain.Entities.Manual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContenidoHTML")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etiquetas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RolesVisibles")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Manuales");
                });

            modelBuilder.Entity("HelpDeskSystem.Domain.Entities.ManualLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<int>("ManualId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ManualId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ManualLogs");
                });

            modelBuilder.Entity("HelpDeskSystem.Domain.Entities.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdjuntoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("HelpDeskSystem.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AsesorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsUrgente")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueEditado")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("SatisfaccionUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AsesorId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("HelpDeskSystem.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPerfilUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "admin@helpdesk.com",
                            FotoPerfilUrl = "",
                            IsActive = true,
                            Nombre = "Administrador Jefe",
                            Password = "$2a$11$2.LI0se.9Yu9ciOs7ep7AOALc1gwhiM.7Ph6co.tEOsk6z4Y5LYd2",
                            Rol = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "juan@helpdesk.com",
                            FotoPerfilUrl = "",
                            IsActive = true,
                            Nombre = "Juan Asesor",
                            Password = "$2a$11$wnobxBfTwCvF3luvG9RB3O8w5NabDY503sR1oPgeUO9.QuQ5ht5BS",
                            Rol = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "carla@cliente.com",
                            FotoPerfilUrl = "",
                            IsActive = true,
                            Nombre = "Carla Usuario",
                            Password = "$2a$11$1N9Vzeg4ofoWCe8XQdofk.RcLnHLsaFjLMIYC7aJlng/lAi1ozCIm",
                            Rol = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Email = "ana@helpdesk.com",
                            FotoPerfilUrl = "",
                            IsActive = true,
                            Nombre = "Ana Asesora",
                            Password = "$2a$11$sAoShInM36jYw8qTy/JvMus7g3KI2uK5WzMjbvCM5d/JH7qu8yo2e",
                            Rol = 2
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Email = "pedro@cliente.com",
                            FotoPerfilUrl = "",
                            IsActive = true,
                            Nombre = "Pedro Cliente",
                            Password = "$2a$11$z2ypKqowxpTlouXAfjEU0.Uy4hF2P6V4QcY73JDOjv9PSwNub.E6C",
                            Rol = 3
                        });
                });

            modelBuilder.Entity("UsuarioCategoria", b =>
                {
                    b.Property<Guid>("AsesoresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoriasId")
                        .HasColumnType("int");

                    b.HasKey("AsesoresId", "CategoriasId");

                    b.HasIndex("CategoriasId");

                    b.ToTable("UsuarioCategoria");

                    b.HasData(
                        new
                        {
                            AsesoresId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CategoriasId = 1
                        },
                        new
                        {
                            AsesoresId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CategoriasId = 2
                        },
                        new
                        {
                            AsesoresId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CategoriasId = 3
                        });
                });

            modelBuilder.Entity("HelpDeskSystem.Domain.Entities.Manual", b =>
                {
                    b.HasOne("HelpDeskSystem.Domain.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("HelpDeskSystem.Domain.Entities.ManualLog", b =>
                {
                    b.HasOne("HelpDeskSystem.Domain.Entities.Manual", "Manual")
                        .WithMany()
                        .HasForeignKey("ManualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDeskSystem.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manual");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HelpDeskSystem.Domain.Entities.Mensaje", b =>
                {
                    b.HasOne("HelpDeskSystem.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDeskSystem.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HelpDeskSystem.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("HelpDeskSystem.Domain.Entities.Usuario", "Asesor")
                        .WithMany()
                        .HasForeignKey("AsesorId");

                    b.HasOne("HelpDeskSystem.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDeskSystem.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asesor");

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UsuarioCategoria", b =>
                {
                    b.HasOne("HelpDeskSystem.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AsesoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDeskSystem.Domain.Entities.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
